### ISSUE TITLE
App store status

### ISSUE THREAD

**Issue by igctw** [pierceboggan/Moments#20]
Hi there,

First of all, thanks for sharing the source code, it always helps me while faced errors on xamarin.forms. But I searched the app on Appstore and Play store, but could not find. Is the app deleted from stores because of some faced  errors/bugs? I just wondered .

Thanks in advance.

**Comment by pierceboggan** [comment]
Nope, I just took down the app because the Azure Mobile Services was deprecated (and is now shut down). You must use Azure Mobile Apps; Moments is not compatible with Azure Mobile Apps, and thus the issue in keeping the app live. :)
