### ISSUE TITLE
Azure Setup -- New Portal 

### ISSUE THREAD

**Issue by pirasathv** [pierceboggan/Moments#22]
I was wondering whether you can guide me on how to get the backend setup using the new Azure Portal . The old portal does not allow creating "Mobile Services" -- issue with URL name already exists. 

Thanks

**Comment by percramer** [comment]
I was wondering the same, does anybody already got it working with the newer mobile app services? Since the old mobile services can't be created anymore.

**Comment by pierceboggan** [comment]
@pirasathv @percramer Great question! I'm working on rewriting a version to use all the new Azure Mobile Apps stuff using ASP.NET Web API (like we did for the [Xamarin Evolve conference app](https://github.com/xamarinhq/app-evolve/), and adding some deployment scripts so you can easily deploy a backend without any configuration.

I'll also work on getting a "test backend" setup so you can download and start playing right away. 👍 

ETA for this is sometime in late July / early August.

**Comment by wiltwitt** [comment]
I was trying to build your version but there are nuget reference issues and some of them don't like Xamarin Forms 2.0 version.  thanks for sharing

**Comment by DaveVoyles** [comment]
Same issue. Can get through parts of the tutorial, but the section:

*Now go to the CONFIGURE tab for your Azure Mobile Service*

Is completely different today. It sounds like I'm cloning the Azure Mobile Service **From** Azure and placing it on my desktop.

**Comment by pierceboggan** [comment]
Yeah, in the process of moving this over from the old (now deprecated) Azure Mobile Services over to Azure Mobile Apps. I'm working on a complete re-write of both service and client layers, so expect to hear back soon. 👍

**Comment by nassarao** [comment]
How is your progress coming along with changing to the new portal? I'd really like to start messing with this.

**Comment by drinvojka** [comment]
Yea i'm waiting on this too .. it seems like the best way to start Xamarin & Azure

**Comment by pierceboggan** [comment]
Got a bit delayed, and haven't begun work on a port. If you're looking for a good temporary example, check out our [new Shopping sample app](https://github.com/Microsoft/XamarinAzure_ShoppingDemoApp) that uses Xamarin + Azure.

**Comment by hellrokr** [comment]
Good to hear. Although I'm trying to port this as well. 

Thanks! Looking forward to it.

**Comment by bobjanacek** [comment]
Pierce, I'm really looking forward to the rewrite with new Azure portal support.  Maybe you have a Xamarin intern that can lend you some dev cycles!

**Comment by TeamBrainStorm** [comment]
any updates on the new port yet?

Please let me know
