### ISSUE TITLE
No service folder to procceed through step 5.3 of the tutorial

### ISSUE THREAD

**Issue by maxpavlov** [pierceboggan/Moments#23]
Hello. I'm setting up Moments for local development. I've been able to navigate in the sea of the new Azure portal to the point where everything seems to be set up and I can clone the mobile app locally to add Azure service code and push.

But whenever I checkout the master branch of the Azure Mobile App, I don't get a 'service' folder which contents I am supposed to replace with the stuff from the repo. 

I have the following checked out stub files (basically Nodejs express based application):
![c0e8cb37866947818037e5b244a4453e](https://cloud.githubusercontent.com/assets/669701/17743174/7959c164-64ab-11e6-9057-50d5b383c620.png)

Should I just create a service folder and proceed as if I had it initially? 
Thanks in advance.

**Comment by pierceboggan** [comment]
Yes, this is due to #22 - the current approach does not work any longer due to the deprecation of Azure Mobile Services.
