### ISSUE TITLE
Custom Renderer class name

### ISSUE THREAD

**Issue by JoyceBabu** [pierceboggan/Moments#24]
Why is the custom renderer class for Android called [`MomentsEntry`](https://github.com/pierceboggan/Moments/blob/master/Moments%20-%20CSharp/Moments.Droid/Controls/MomentsEntry.cs#L10), while the class for iOS is called [`MomentsEntryRenderer`](https://github.com/pierceboggan/Moments/blob/master/Moments%20-%20CSharp/Moments.iOS/Controls/MomentsEntry.cs#L10)? Is the `Renderer` suffix purposefully dropped from Droid project?

**Comment by pierceboggan** [comment]
@JoyceBabu: There's no reason, really. I should be using the same naming conventions. The important thing is the registration of the dependency with the attribute. The dependency resolver doesn't really care what the name of the class is. 👍

**Comment by JoyceBabu** [comment]
Thank you for the clarification.
