### ISSUE TITLE
System.Net.Http.Primitives Critical Error

### ISSUE THREAD

**Issue by pvcove** [pierceboggan/Moments#26]
Getting two critical errors that I can't find a solution for....

1) Error Failed to resolve assembly: 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Moments.iOS

2) Error NuGet Package restore failed for project Moments.Analysis: Unable to find version '4.0.11' of package 'System.Net.Http.Primitives'.
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages: Package 'System.Net.Http.Primitives.4.0.11' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
https://www.nuget.org/api/v2/: Package 'System.Net.Http.Primitives.4.0.11' is not found on source 'https://www.nuget.org/api/v2/'.
https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'System.Net.Http.Primitives.4.0.11' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.

I’ve tried many of the “Answers” on Stackoverflow without resolve. And I’ve looked high and low in other forums as well.

The environment in use has been proven stable as I've successfully debugged code in Visual Studio while simultaneously running the iOS simulator on a Mac. Have also debugged from a device connected to the Mac.

**Comment by SamArmand** [comment]
Having the same issues. Nothing on StackOverflow worked for me either.

**Comment by pvcove** [comment]
Thanks Sam.  If you find a solution please post!  I'll do likewise.

**Comment by SamArmand** [comment]
Will do. Working on it now.

**Comment by SamArmand** [comment]
@pvcove Haven't been able to fix it. Use the XAML project instead. That one builds fine.
