### ISSUE TITLE
Image captured is lower resolution than the native camera resolution

### ISSUE THREAD

**Issue by owlstack** [pierceboggan/Moments#27]
@pierceboggan On my phone's native camera, I am taking photos with resolution:  2576x1932. When I'm using the approach highlighted here, the textureView width and height are only 1451x720, which is much smaller than the native camera resolution. I am wondering why the discrepancy? Where does OnSurfaceTextureAvailable() grab the width and height in this scenario? Or how is the width and height set for the textureView when it's set?

**Comment by pierceboggan** [comment]
@owlstack: Interesting! Honestly, it's been _so_ long since I've looked at this code I couldn't give an intelligent answer. Either way, the "correct" way to implement this is by using the new Camera2 APIs, which are much nicer and give a bit more control to us over things like resolution.
